### ISSUE TITLE
pypi package 

### ISSUE THREAD

**Issue by greedo** [hobbeswalsh/flask-sillywalk#13]
This is a great package, it just needs to be added to pypi to make it easier to distribute.

**Comment by delijati** [comment]
There is a relase on pypi but its not the one from github. To make the process of uploading a new version easier i suggest to use https://pypi.python.org/pypi/zest.releaser or https://pypi.python.org/pypi/jarn.mkrelease and to install https://pypi.python.org/pypi/setuptools-git

**Comment by hobbeswalsh** [comment]
Ok, done.

https://pypi.python.org/pypi/Flask-Sillywalk/2.1

Thanks!
