### ISSUE TITLE
Travis CI hook activation

### ISSUE THREAD

**Issue by delijati** [hobbeswalsh/flask-sillywalk#16]
I prepared the project to support the TravisCI hook now only this steps are necessary to activate it.

* Toggle the switch on one of your projects and then click on little wrench icon to open the project's Service Hooks page on GitHub. To get to the same place from your GitHub project, go to Settings > Service Hooks.

* On the Service Hooks page scroll down to Travis and you'll notice that the hook is already activated. Click on "Travis".

**Comment by hobbeswalsh** [comment]
ok, https://travis-ci.org/hobbeswalsh/flask-sillywalk

will get tot he pypi packaging when I get the time. thanks!

**Comment by hobbeswalsh** [comment]
@delijati I don't have a lot of familiarity with Python 3 -- do you recognize this error from the Travis build against python 3?

https://travis-ci.org/hobbeswalsh/flask-sillywalk/jobs/53065520
